/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		OAUTH_KV: KVNamespace;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		HOSTED_DOMAIN: string;
		COOKIE_ENCRYPTION_KEY: string;
		BASE_URL: string;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").BoilerplateMCP>;
		APOLLO_API_KEY: string; // Add this line
	}
}
interface Env extends Cloudflare.Env {}